put:
  tags:
    - Admin
  summary: Update application (Admin)
  description: Update application details
  parameters:
    - name: id
      in: path
      required: true
      schema:
        type: integer
      description: Application ID
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: ../components/schemas/UpdateApplicationRequest.yaml
  responses:
    '200':
      description: Application updated
      content:
        application/json:
          schema:
            $ref: ../components/schemas/ApiResponse.yaml
    '400':
      $ref: ../components/responses/BadRequest.yaml
    '401':
      $ref: ../components/responses/Unauthorized.yaml
    '403':
      $ref: ../components/responses/Forbidden.yaml
    '404':
      $ref: ../components/responses/NotFound.yaml
delete:
  tags:
    - Admin
  summary: Delete application (Admin)
  description: Delete an application
  parameters:
    - name: id
      in: path
      required: true
      schema:
        type: integer
      description: Application ID
  responses:
    '200':
      description: Application deleted
      content:
        application/json:
          schema:
            $ref: ../components/schemas/ApiResponse.yaml
    '400':
      $ref: ../components/responses/BadRequest.yaml
    '401':
      $ref: ../components/responses/Unauthorized.yaml
    '403':
      $ref: ../components/responses/Forbidden.yaml
    '404':
      $ref: ../components/responses/NotFound.yaml
