openapi: 3.0.3
info:
  title: Crocodile Backend API
  description: >-
    A comprehensive API for managing AI models, applications, user
    authentication, detection records, and benchmarking
  version: 1.0.0
  contact:
    name: Crocodile API Support
    url: 'https://crocodile.store'
servers:
  - url: 'http://localhost:8080/api'
    description: Local development server
  - url: 'https://api.crocodile.store/api'
    description: Production server
security:
  - BearerAuth: []
paths:
  /:
    $ref: paths.yaml
  /user/register:
    $ref: paths/user@register.yaml
  /user/login:
    $ref: paths/user@login.yaml
  /user:
    $ref: paths/user.yaml
  /model:
    $ref: paths/model.yaml
  /model/public:
    $ref: paths/model@public.yaml
  /model/all:
    $ref: paths/model@all.yaml
  /model/final-benchmark:
    $ref: paths/model@final-benchmark.yaml
  '/model/{id}':
    $ref: 'paths/model@{id}.yaml'
  '/model/{id}/upload-url':
    $ref: 'paths/model@{id}@upload-url.yaml'
  '/model/{id}/upload/complete':
    $ref: 'paths/model@{id}@upload@complete.yaml'
  '/model/{id}/download-url':
    $ref: 'paths/model@{id}@download-url.yaml'
  '/model/{id}/quantization':
    $ref: 'paths/model@{id}@quantization.yaml'
  '/model/{id}/quantization/{quantizationId}':
    $ref: 'paths/model@{id}@quantization@{quantizationId}.yaml'
  '/model/{id}/quantization/{quantizationId}/format':
    $ref: 'paths/model@{id}@quantization@{quantizationId}@format.yaml'
  '/model/{id}/quantization/{quantizationId}/format/{format}/upload-url':
    $ref: >-
      paths/model@{id}@quantization@{quantizationId}@format@{format}@upload-url.yaml
  '/model/{id}/quantization/{quantizationId}/format/{format}/upload/complete':
    $ref: >-
      paths/model@{id}@quantization@{quantizationId}@format@{format}@upload@complete.yaml
  '/model/{id}/quantization/{quantizationId}/format/{format}/download-url':
    $ref: >-
      paths/model@{id}@quantization@{quantizationId}@format@{format}@download-url.yaml
  '/model/{id}/quantization/{quantizationId}/format/{formatId}':
    $ref: 'paths/model@{id}@quantization@{quantizationId}@format@{formatId}.yaml'
  /detection:
    $ref: paths/detection.yaml
  '/detection/{id}':
    $ref: 'paths/detection@{id}.yaml'
  '/detection/{id}/complete':
    $ref: 'paths/detection@{id}@complete.yaml'
  /benchmark:
    $ref: paths/benchmark.yaml
  /benchmark/deep-analysis:
    $ref: paths/benchmark@deep-analysis.yaml
  /benchmark/deep-analysis/already:
    $ref: paths/benchmark@deep-analysis@already.yaml
  /application:
    $ref: paths/application.yaml
  '/application/{id}/download':
    $ref: 'paths/application@{id}@download.yaml'
  /admin/application:
    $ref: paths/admin@application.yaml
  '/admin/application/{id}/upload':
    $ref: 'paths/admin@application@{id}@upload.yaml'
  '/admin/application/{id}/hide':
    $ref: 'paths/admin@application@{id}@hide.yaml'
  '/admin/application/{id}/active':
    $ref: 'paths/admin@application@{id}@active.yaml'
  '/admin/application/{id}':
    $ref: 'paths/admin@application@{id}.yaml'
  '/admin/application/{id}/commit-download':
    $ref: 'paths/admin@application@{id}@commit-download.yaml'
  /helper/unique-target-animal:
    $ref: paths/helper@unique-target-animal.yaml
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
tags:
  - name: Health
    description: System health and status endpoints
  - name: Authentication
    description: User authentication and management
  - name: Models
    description: AI model management
  - name: Quantization
    description: Model quantization management
  - name: Formats
    description: Quantization format management
  - name: Detection
    description: Detection record management
  - name: Benchmark
    description: Benchmarking and performance analysis
  - name: Applications
    description: Mobile application management
  - name: Admin
    description: Administrative functions
  - name: Helpers
    description: Utility endpoints
